spring: 
  application:
    name: jv-eureka-server
# 端口设置
server:
  port: 8761
# 注册中心配置
eureka:
  server:
    enable-self-preservation: true       # 关闭自我保护模式（缺省为打开）
    eviction-interval-timer-in-ms: 30000   # 续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）
  instance:
    hostname: peer1
  client:
    register-with-eureka: true   # true代表向注册中心注册自己
    fetch-registry: false   # 注册中心的职责就是维护服务实例，true表示需要检索服务
    service-url:
     defaultZone: http://peer2:8761/eureka